In [93]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [94]:
df_artistas=pd.read_csv("data/artists.csv")
df_escuchas=pd.read_csv("data/listeners.csv")
df_mas_streams=pd.read_csv("data/Spotify_most_streamed.csv")

In [95]:
df_artistas.head()

         Artist   Streams   Daily   As lead      Solo As feature
0         Drake  85,041.3  50.775  57,252.6  32,681.6   27,788.7
1     Bad Bunny  67,533.0  44.820  40,969.6  23,073.0   26,563.4
2  Taylor Swift  57,859.0  85.793  55,566.7  50,425.7    2,292.4
3    The Weeknd  53,665.2  44.437  42,673.3  31,164.2   10,991.9
4    Ed Sheeran  47,907.7  17.506  42,767.9  33,917.0    5,139.8

In [96]:
df_escuchas.head()

         Artist    Listeners Daily Trend  Peak  PkListeners
0    The Weeknd  107,592,328    -138,880     1  113,034,886
1  Taylor Swift  101,003,302         889     2  101,003,302
2    Ed Sheeran   76,475,126     -68,137     2   87,934,910
3      Dua Lipa   76,421,916     -71,356     4   77,778,397
4     Bad Bunny   76,162,057    -199,052     3   83,950,570

In [97]:
df_mas_streams.head()

                    Artist and Title        Streams      Daily
0       The Weeknd - Blinding Lights  3,783,983,806  1,736,378
1          Ed Sheeran - Shape of You  3,616,649,759  1,135,140
2  Lewis Capaldi - Someone You Loved  2,958,875,491  1,522,093
3            Post Malone - Sunflower  2,898,311,408  1,871,177
4         Tones And I - Dance Monkey  2,896,024,418    666,818

In [98]:
print(df_escuchas.columns)
print(df_mas_streams.columns)
print(df_artistas.columns)

Index(['Artist', 'Listeners', 'Daily Trend', 'Peak', 'PkListeners'], dtype='str')
Index(['Artist and Title', 'Streams', 'Daily'], dtype='str')
Index(['Artist', 'Streams', 'Daily', 'As lead', 'Solo', 'As feature'], dtype='str')

## Limpieza de espacios

In [99]:
df_artistas.columns = df_artistas.columns.str.strip()
df_escuchas.columns = df_escuchas.columns.str.strip()
df_mas_streams.columns = df_mas_streams.columns.str.strip()

Verificación de valores nulos

In [100]:
print(df_artistas.isnull().sum())
print(df_escuchas.isnull().sum())
print(df_mas_streams.isnull().sum())

Artist          0
Streams         0
Daily           6
As lead        16
Solo           69
As feature    338
dtype: int64
Artist         0
Listeners      0
Daily Trend    0
Peak           0
PkListeners    0
dtype: int64
Artist and Title    0
Streams             0
Daily               3
dtype: int64

- Se remplazan los valores nulos por 0 en el dataframe de artistas
- Se eliminan las filas con valores nulos en el dataframe de mas_streams

In [101]:
df_artistas = df_artistas.fillna(0)
df_mas_streams=df_mas_streams.dropna()

Separar la columna artist and title del dataframe df_mas_streams para realizar el analisis por separado

In [104]:
df_mas_streams[['Artist','Title']] = df_mas_streams['Artist and Title'].str.split(' - ', n=1, expand=True)

In [105]:
df_mas_streams

,Artist and Title,Streams,Daily,Artist,Title
0,The Weeknd - Blinding Lights,"3,783,983,806","1,736,378",The Weeknd,Blinding Lights
1,Ed Sheeran - Shape of You,"3,616,649,759","1,135,140",Ed Sheeran,Shape of You
2,Lewis Capaldi - Someone You Loved,"2,958,875,491","1,522,093",Lewis Capaldi,Someone You Loved
3,Post Malone - Sunflower,"2,898,311,408","1,871,177",Post Malone,Sunflower
4,Tones And I - Dance Monkey,"2,896,024,418","666,818",Tones And I,Dance Monkey
...,...,...,...,...,...
2495,Richard Marx - Right Here Waiting,"399,549,516","250,073",Richard Marx,Right Here Waiting
2496,The Neighbourhood - You Get Me So High,"399,218,096","617,797",The Neighbourhood,You Get Me So High
2497,Clairo - Bubble Gum,"398,936,748","370,661",Clairo,Bubble Gum
2498,Bing Crosby - White Christmas,"398,725,594","1,250,615",Bing Crosby,White Christmas
2499,Shaggy - Angel,"398,310,263","339,498",Shaggy,Angel

Se cambia el tipo de variable de String a int de las columnas Streams y Dayli

In [109]:
df_mas_streams['Streams'] = df_mas_streams['Streams'].str.replace(',', '')
df_mas_streams['Streams'] = pd.to_numeric(df_mas_streams['Streams'])

In [110]:
df_mas_streams['Daily']=df_mas_streams['Daily'].str.replace(',', '')
df_mas_streams['Daily'] = pd.to_numeric(df_mas_streams['Daily'])

In [118]:
df_mas_streams.info()

top_songs = df_mas_streams.sort_values(by='Streams', ascending=False).head(10)

<class 'pandas.DataFrame'>
Index: 2497 entries, 0 to 2499
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist and Title  2497 non-null   str
 1   Streams           2497 non-null   int64
 2   Daily             2497 non-null   int64
 3   Artist            2497 non-null   str
 4   Title             2497 non-null   str
dtypes: int64(2), str(3)
memory usage: 117.0 KB